#!/bin/bash
mkdir ./results/
num_steps_batch=100
num_steps=5e6
entropy_c=0.1 
gamm=0.9
li=100000


python -m baselines.run --alg=a2c --env=PerceptualDecisionMaking-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 > ./results/res.out

python -m baselines.run --alg=a2c --env=DelayedComparison-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=ContextDecisionMaking-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=economicDecisionMaking-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=PostDecisionWager-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=DelayPairedAssociation-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=GoNogo-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=PerceptualDecisionMaking_hist-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=ReadySetGo-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=DelayedMatchSample-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out

python -m baselines.run --alg=a2c --env=DawTwoStep-v0 --network=lstm --nsteps=$num_steps_batch --num_timesteps=$num_steps --log_interval=$li --ent_coef=$entropy_c --lrschedule=constant --gamma=$gamm --num_env=12 >> ./results/res.out



