name: notebooks

on:
  push:
    paths-ignore:
      # specific folder locations
      - ".vscode/**"
      # filetypes
      - "**.md"
      - "**.rst"
      - "**.cff"
      - "**.png"
    branches:
      - main
  pull_request:
    # types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      # specific folder locations
      - ".vscode/**"
      # filetypes
      - "**.md"
      - "**.rst"
      - "**.cff"
      - "**.png"

jobs:
  run_notebooks:
    # if: github.event.pull_request.draft == false
    # name: Run notebooks
    runs-on: ubuntu-latest

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python info
        run: |
          which python3
          python3 --version

      - name: Get changed files
        id: changed
        run: |
          set -e
          git fetch origin ${{ github.base_ref }}
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "changed_files"
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "changed_files"
          echo "EOF" >> $GITHUB_OUTPUT
          echo "changed_files"

      - name: Check if only notebooks changed
        id: only-notebooks
        run: |
          set -e
          if echo "${{ steps.changed.outputs.changed_files }}" | grep -vE '\.ipynb$|\.yml$' | grep -q '.'; then
            echo "only_notebooks=false" >> $GITHUB_OUTPUT
          else
            echo "only_notebooks=true" >> $GITHUB_OUTPUT
          fi

      - name: Get changed notebooks
        id: changed-notebooks
        if: steps.only-notebooks.outputs.only_notebooks == 'true'
        run: |
          set -e
          NOTEBOOKS=$(echo "${{ steps.changed.outputs.changed_files }}" | grep '\.ipynb$' || true)
          echo "notebooks=$NOTEBOOKS" >> $GITHUB_OUTPUT

      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install .[rl,dev,notebooks]

      - name: Run only changed notebooks
        if: steps.only-notebooks.outputs.only_notebooks == 'true' && steps.changed-notebooks.outputs.notebooks != ''
        run: |
          set -e
          echo "${{ steps.changed-notebooks.outputs.notebooks }}" | xargs pytest --nbmake --durations=0

      - name: Run all notebooks
        if: steps.only-notebooks.outputs.only_notebooks != 'true'
        run: |
          set -e
          pytest --nbmake docs --durations=0
