name: Build and upload to PyPI, deploy documentation

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build universal wheel and source distribution
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip, install dependencies and the package
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev,publishing]
      - name: Build wheel and source distribution
        run: python3 -m build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*

  # TODO: Enable this and make it a requirement for the real PyPI
  # upload_test_pypi:
  #   needs:
  #     - build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/p/neurogym
  #   permissions:
  #     id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
  #   steps:
  #     - name: Download all the dists
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-package-distributions
  #         path: dist/
  #     # Retrieve your distributions here.
  #     # NOTE: Using a specific commit to avoid security issues caused by rogue tags
  #     # This should be updated regularly.
  #     - name: Publish package distributions to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@ed0c539

  upload_pypi:
    needs:
      - build
      # TODO: Enable this once the previous action is set up.
      # - upload_test_pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/neurogym
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      # Retrieve your distributions here
      # NOTE: Using a specific commit to avoid security issues caused by rogue tags.
      # This should be updated regularly.
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c539

  deploy_docs:
    name: Deploy documentation
    needs: upload_pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-tags: true
      - name: Fetch gh-pages
        run: git fetch origin gh-pages:gh-pages
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install requirements
        run: python3 -m pip install .[dev]
      - name: Configure git
        run: |
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git config -l
      - name: Build documentation
        run: |
          version=$(git describe --tags --abbrev=0)
          mike deploy -p -u $version latest
